#
# Deploy IBGP and EBGP routing in a WAN fabric
#
---
- name: Create and deploy BGP configurations
  hosts: all
  vars:
    configs: "{{inventory_dir}}/configs"
  tasks:
  - include_vars: "{{ item }}"
    with_first_found:
      - nodes.yml
      - "{{ inventory_dir }}/nodes.yml"
    tags: [ configs,verify,deploy ]
  - include: ../tools/clean.yml
    tags: [ clean ]
  - include: config_bgp.yml
    tags: [ configs ]
  - include: deploy_bgp.yml
    tags: [ deploy ]
  - include: verify_bgp.yml
    tags: [ verify ]
