djohnkind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  #podSubnet: "10.244.0.0/16"
  #serviceSubnet: "10.96.0.0/12"
# 1 control plane node and 2 workers
nodes:
# the control plane node config
- role: control-plane
  extraMounts:
  - hostPath: /home/djohn/Downloads/cni-plugins-linux-amd64-v0.8.6/
    containerPath: /opt/cni/bin/
    readOnly: false  
# the three workers
- role: worker
  extraMounts:
  - hostPath: /home/djohn/Downloads/cni-plugins-linux-amd64-v0.8.6/
    containerPath: /opt/cni/bin/
    readOnly: false
- role: worker
  extraMounts:
  - hostPath: /home/djohn/Downloads/cni-plugins-linux-amd64-v0.8.6/
    containerPath: /opt/cni/bin/
    readOnly: false

