apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kuardelb
  name: kuardelb
spec:
  externalIPs:
  - 6.6.6.6
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuardelb
  type: LoadBalancer
status:
  loadBalancer: {}
