somesayhttps://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/

kubectl proxy --port=8001 &

download default config 
NODE_NAME=kind-control-plane; curl -sSL "http://localhost:8001/api/v1/nodes/${NODE_NAME}/proxy/configz" | jq '.kubeletconfig|.kind="KubeletConfiguration"|.apiVersion="kubelet.config.k8s.io/v1beta1"' > kubelet_configz_${NODE_NAME}

kubectl -n kube-system create configmap fucking-kubelet --from-file=kubelet=kubelet_configz_kind-control-plane --append-hash -o yaml


kubectl patch node kind-control-plane -p "{\"spec\":{\"configSource\":{\"configMap\":{\"name\":\"fucking-kubelet-7kk9222t48\",\"namespace\":\"kube-system\",\"kubeletConfigKey\":\"kubelet\"}}}}"
kubectl patch node kind-worker -p "{\"spec\":{\"configSource\":{\"configMap\":{\"name\":\"fucking-kubelet-7kk9222t48\",\"namespace\":\"kube-system\",\"kubeletConfigKey\":\"kubelet\"}}}}"
kubectl patch node kind-worker2 -p "{\"spec\":{\"configSource\":{\"configMap\":{\"name\":\"fucking-kubelet-7kk9222t48\",\"namespace\":\"kube-system\",\"kubeletConfigKey\":\"kubelet\"}}}}"


##manual
kubectl edit node kind-control-plane
kubectl edit node kind-worker
kubectl edit node kind-worker2
under spec add this
configSource:
    configMap:
        name: new-kubelet # replace CONFIG_MAP_NAME with the name of the ConfigMap
        namespace: kube-system
        kubeletConfigKey: kubelet

~/kuber-deployment/kubernetes-best-prac
$kubectl get no kind-control-plane -o json | jq '.status.config'
null
~/kuber-deployment/kubernetes-best-prac
$kubectl get no kind-worker -o json | jq '.status.config'
null
~/kuber-deployment/kubernetes-best-prac
$kubectl get no kind-worker2 -o json | jq '.status.config'
null
~/kuber-deployment/kubernetes-best-prac
$

kubectl patch node kind-control-plane -p "{\"spec\":{\"configSource\":{\"configMap\":{\"name\":\"fucking-kubelet-7kk9222t48\",\"namespace\":\"kube-system\",\"kubeletConfigKey\":\"kubelet\"}}}}"
kubectl patch node kind-worker -p "{\"spec\":{\"configSource\":{\"configMap\":{\"name\":\"fucking-kubelet-7kk9222t48\",\"namespace\":\"kube-system\",\"kubeletConfigKey\":\"kubelet\"}}}}"
kubectl patch node kind-worker2 -p "{\"spec\":{\"configSource\":{\"configMap\":{\"name\":\"fucking-kubelet-7kk9222t48\",\"namespace\":\"kube-system\",\"kubeletConfigKey\":\"kubelet\"}}}}"


systemctl daemon-reload && systemctl restart kubelet