[global.config]
  as = 4294967291
  router-id = "100.100.11.44"
# MJQPOC212SW01
[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.16.11.254" #uplayer bgp router.
    peer-as = 65534
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv4-unicast"
    [neighbors.afi-safis.mp-graceful-restart.config]
      enabled = true
  [neighbors.graceful-restart.config]
    enabled = true
    restart-time = 600
  [neighbors.ebgp-multihop.config]
    enabled = true
    multihop-ttl = 255
  [neighbors.route-server.config]
    route-server-client = true
  [neighbors.apply-policy.config]
    export-policy-list = ["policy-65534"]
    default-import-policy = "reject-route"
    default-export-policy = "reject-route"

[[defined-sets.bgp-defined-sets.community-sets]]
  community-set-name = "pc-65534"
  community-list = ["65534"]

[[policy-definitions]]
  name = "policy-65534"
  [[policy-definitions.statements]]
    name = "ps-65534"
    [policy-definitions.statements.conditions.bgp-conditions.match-community-set]
      community-set = "pc-65534"
    [policy-definitions.statements.actions]
      route-disposition = "accept-route"
    [policy-definitions.statements.actions.bgp-actions.set-as-path-prepend]
      as = 4294967291
      repeat-n = 1