apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: weave-scope
    name: weave-scope-app
    weave-cloud-component: scope
    weave-scope-component: app
  name: weave-scope-app
spec:
  ports:
  - port: 4040
    protocol: TCP
    targetPort: 4040
    nodePort: 32404
  selector:
    app: weave-scope
    name: weave-scope-app
    weave-cloud-component: scope
    weave-scope-component: app
  type: NodePort
status:
  loadBalancer: {}