#
# Create OSPF configuration
#
---
- name: Create configuration directory
  local_action: file path={{configs}} state=directory
  run_once: true
  check_mode: no
  changed_when: no

- name: Create configurations
  template: src=ospf-config.j2 dest={{configs}}/{{inventory_hostname}}.ospf.cfg
  check_mode: no
