apiVersion: v1
kind: Pod
metadata:
  name: access
  namespace: policy-demo
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
