---
- hosts: ios_devices-switch
  gather_facts: no
  connection: local

  tasks:
  - name: Include Login Credentials
    include_vars: secrets.yml

  - name: Define Provider
    set_fact:
      provider:
        host: "{{ ansible_host }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"

  - name: RUN 'trunk-port'
    ios_config:
      provider: "{{ provider }}"
      lines:
      - int range gigabitEthernet 0/0 - 3 , gigabitEthernet 1/0 -3
      - switchport trunk encapsulation dot1q
      - spanning-tree bpdufilter enable
      - switchport mode trunk
      - spanning-tree portfast edge trunk  
      - no shutdown
  


