---
- hosts: ios_devices-router
  gather_facts: no
  connection: local

  tasks:
  - name: Include Login Credentials
    include_vars: secrets.yml
  - name: Define Provider
    set_fact:
      provider_R1:
        host: "{{ ansible_host_R1 }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
      provider_R2:
        host: "{{ ansible_host_R2 }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"  
      Vlan_TAG_ODD_IP: {
        "12": {"description": "hitler", "ip": "169.254.12.2", "Subnets": "255.255.255.252"},
        "13": {"description": "hitler", "ip": "169.254.13.2", "Subnets": "255.255.255.252"},
        "14": {"description": "hitler", "ip": "169.254.14.2", "Subnets": "255.255.255.252"}
      }
      Vlan_TAG_EVEN_IP: {
        "12": {"description": "hitler", "ip": "169.254.12.1", "Subnets": "255.255.255.252"},
        "13": {"description": "hitler", "ip": "169.254.13.1", "Subnets": "255.255.255.252"},
        "14": {"description": "hitler", "ip": "169.254.14.1", "Subnets": "255.255.255.252"}
      }    
 
  - name: RUN 'Configure IP ADDRESS WITH ODD Number'
    ios_config:
      provider: "{{ provider_R1 }}"
      lines:
      - description {{ item.value.description }}
      - encapsulation dot1Q {{ item.key }}
      - ip address {{ item.value.ip }} {{ item.value.Subnets }}
      - no shutdown
      - ip ospf 1 area 0
      parents: interface GigabitEthernet1.{{ item.key }}
    with_dict: "{{ Vlan_TAG_ODD_IP }}"  

  - name: RUN 'Configure IP ADDRESS WITH EVEN Number'
    ios_config:
      provider: "{{ provider_R2 }}"
      lines:
      - description {{ item.value.description }}
      - encapsulation dot1Q {{ item.key }}
      - ip address {{ item.value.ip }} {{ item.value.Subnets }}
      - no shutdown
      - ip ospf 1 area 0
      parents: interface GigabitEthernet1.{{ item.key }}
    with_dict: "{{ Vlan_TAG_EVEN_IP }}"  

  - name: RUN 'show ip interface brief'
    ios_command:
      provider: "{{ provider_R2 }}"
      commands:
        - show ip interface brief
    register: ip_interface
    
  - debug: var=ip_interface.stdout_lines

  - name: Check the running against master Configure
    ios_config:
      provider: "{{ provider_R2 }}"
      diff_against: startup
      diff_ignore_lines:
        - ntp clock .*

  - name: save running to startup when modified
    ios_config:
      provider: "{{ provider_R2 }}"
      save_when: modified




