apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kuard
  name: kuard
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30001
  selector:
    app: kuard
  type: LoadBalancer
status:
  loadBalancer: {}
