apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kuard-np
  name: kuard-np
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32700
  selector:
    app: kuard-np
  type: NodePort
status:
  loadBalancer: {}