---
- hosts: ios_devices*
  gather_facts: no
  connection: local
  strategy: debug

  tasks:
  - name: Include Login Credentials
    include_vars: secrets.yml

  - name: Define Provider
    set_fact:
      provider:
        host: "{{ ansible_host }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"

  - name: Define Provider (Enable)
    when: inventory_hostname in groups.ios_devices_enable
    set_fact:
        enable:
            auth_pass: "{{ creds['auth_pass'] }}"
            authorize: yes

  - name: Update Provider (Enable)
    when: inventory_hostname in groups.ios_devices_enable
    set_fact:
        provider: "{{ provider | combine(enable) }}"

  - name: BACKUP
    ios_config:
      provider: "{{ provider }}"
      backup: yes

  - name: RUN 'Set DNS'
    ios_config:
      provider: "{{ provider }}"
      lines:
        - ip name-server 8.8.8.8
        - ip name-server 8.8.4.4
    register: set_dns

  - name: CHECK CHANGE - dns
    when: "(set_dns.changed == true)"
    set_fact: configured=true

  - name: RUN 'Set NTP'
    ios_config:
      provider: "{{ provider }}"
      lines:
        - ntp server uk.pool.ntp.org
        - ntp server time.apple.com
    register: set_ntp

  - name: CHECK CHANGE - ntp
    when: "(set_ntp.changed == true)"
    set_fact: configured=true

  - name: RUN 'wr mem'
    when: "(configured is defined) and (configured == true)"
    register: save_config
    ios_command:
      provider: "{{ provider }}"
      commands:
        - "write memory"
