#
# Deploy IBGP and EBGP routing in a WAN fabric
#
---
- name: Create configuration directory
  local_action: file path={{configs}} state=directory
  run_once: true
  check_mode: no
  changed_when: no
  tags: [ configs ]

- name: Create configurations
  template: src=bgp-config.j2 dest={{configs}}/{{inventory_hostname}}.bgp.cfg
  check_mode: no
  changed_when: no
  tags: [ configs ]
