apiVersion: batch/v1
kind: Job
metadata:
  name: bpf-kernel-check
spec:
  template:
    spec:
      nodeSelector:
      # e. g. node.kubernetes.io/cni: cilium
      containers:
        - name: cilium
          image: docker.io/cilium/cilium:latest
          command: ["cilium", "kernel-check"]
      restartPolicy: Never
  backoffLimit: 1
